name: Build and Test

on:
  push:
    paths:
      - 'src/ccc/ccc.cpp'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install llvm
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get install llvm clang libclang-dev
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install llvm
          fi
      - name: Set up LLVM
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "/usr/lib/llvm/bin" >> $GITHUB_PATH
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH
          fi
      - name: Print PATH
        shell: bash
        run: echo $PATH
      - name: List LLVM directory
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            ls "C:/Program Files/LLVM/bin"
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            ls /usr/lib/llvm/bin
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            ls /usr/local/opt/llvm/bin
          fi
      - name: Build
        shell: bash
        run: |
          g++ src/ccc/ccc.cpp -o ccc $(llvm-config --cxxflags) $(llvm-config --ldflags) -lclang $(llvm-config --libs --system-libs)

