name: Build and Test

on:
  push:
    paths:
      - 'src/ccc/ccc.cpp'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get install llvm clang libclang-dev
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install llvm
          fi
      - name: Set up LLVM
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH
          fi
      - name: Build
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            clang++ src/ccc/ccc.cpp -o ccc --target=x86_64-pc-windows-gnu
          else
            g++ src/ccc/ccc.cpp -o ccc $(llvm-config --cxxflags) $(llvm-config --ldflags) -lclang $(llvm-config --libs --system-libs)
          fi

